version: '3'
services:
  api_container:
    build: 
      context: api_container
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - 8000:80
    restart: always

  pipeline_container:
    build:
      context: pipeline_container
      dockerfile: Dockerfile
    container_name: pipeline_container
    restart: always
    ports:
      - 8001:8080
    volumes:
      - ./data:/usr/local/airflow/data
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False